name: Code - Feature / Bug
description: As a developer this is a useful intake for creating a feature or bug.
body:
  - type: textarea
    id: textarea
    attributes:
      label: textarea
      description: Add a description
      placeholder:
    validations:
      required: false