name: Create 
description: Create a Talk
title: '[Talk Submission] '
labels: ['talk-submission']
assignees: '@reggi'
body:
  - type: input
    id: name
    attributes:
      label: name
      description: Please enter the name of the speaker.
      placeholder:
    validations:
      required: false

  - type: input
    id: githubUsername
    attributes:
      label: githubUsername
      description: Please enter the GitHub username. (No @ symbol needed.)
      placeholder:
    validations:
      required: false

  - type: input
    id: linkedin
    attributes:
      label: linkedin
      description: Please enter the LinkedIn profile URL.
      placeholder:
    validations:
      required: false

  - type: input
    id: website
    attributes:
      label: website
      description: Please enter the personal or professional website URL.
      placeholder:
    validations:
      required: false

  - type: textarea
    id: profileImage
    attributes:
      label: profileImage
      description: Please profile a profile image URL. (If none is provided we use the GitHub profile image, or [the default image](https://github.com/astoria-tech/meetup/blob/main/packages/image-generator/banner/default.png))
      placeholder:
    validations:
      required: false

  - type: input
    id: title
    attributes:
      label: title
      description: 'The title of your presentation.'
      placeholder:
    validations:
      required: false

  - type: input
    id: date
    attributes:
      label: date
      description: 'The date of the presentation (YYYY-MM-DD).'
      placeholder: 'YYYY-MM-DD'
    validations:
      required: false

  - type: textarea
    id: slides
    attributes:
      label: slides
      description: 'Link to the presentation slides, (if available).'
      placeholder: 'https://yoursite.com/slides.pdf'
    validations:
      required: false

  - type: input
    id: slidesSource
    attributes:
      label: slidesSource
      description: 'Link to the source of the slides, if applicable (e.g., Google Drive, Your personal website).'
      placeholder:
    validations:
      required: false
