#!/usr/bin/env node
import {$} from 'zx'

const diff = await $`git diff --name-only HEAD HEAD~1 -- 'src/content/events/'`
const changes = diff.stdout
  .trim()
  .split('\n')
  .map(v => {
    return v.replace('src/content/events/', '').replace('-event.md', '')
  })

if (changes.length !== 1) {
  throw new Error('Expected exactly one change')
}

process.stdout.write(changes[0])
