name: Check Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Use the workflow in this repo
        uses: ./.github/workflows/dispatch-check.yml
        with:
          branch: main
