name: Check

# responsible for checking the the code is in good
# working order, before merging (or while its in main)

on:
  issue_comment:
    types: [created]
  push:
    paths-ignore:
      - 'design/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'
        required: true
        type: string
  workflow_call:
    inputs:
      branch:
        description: 'Branch Name'
        required: true
        type: string
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check conditions and exit
        if: (github.event_name == 'issue_comment') && (github.event.comment.body != '.check')
        run: exit 1

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref || github.event.inputs.branch || 'main' }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Set this to the node version you are using

      - name: Install dependencies
        run: npm install

      - name: Run style check
        run: npm run style

      - name: Run lintpkg
        run: npm run lintpkg

      - name: Run Build
        run: npm run build
