name: Create Image on Event Change

on:
  push:
    branches:
      - main
    paths:
      - 'src/content/events/**'

jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.check-file.outputs.date }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check and get changed file
        id: check-file
        run: |
          echo "date=$(./script/eventchanged)" >> $GITHUB_OUTPUT

  create-image:
    needs: changed
    uses: ./.github/workflows/create-image-call-dispatch.yml
    with:
      date: ${{ needs.changed.outputs.date }}
