name: Create PR to Fix Styles

on:
  workflow_dispatch:

permissions: write-all

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate unique branch name
        id: branchname
        run: |
          # Using a combination of the event date and a unique suffix (UUID)
          echo "branchname=style-$(uuidgen)" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: git checkout -b ${{ steps.branchname.outputs.branchname }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Set this to the node version you are using

      - name: Install dependencies
        run: npm install

      - name: Run style check
        run: npm run style:fix

      - name: Commit files
        run: |
          git add .
          git commit -m "Fix Styles"

      - name: Push changes
        run: git push origin ${{ steps.branchname.outputs.branchname }}

      - name: Create PR
        uses: actions/github-script@v6
        with:
          script: |
            const headBranch = '${{ steps.branchname.outputs.branchname }}';
            const baseBranch = 'main'; // Ensure this matches your repo's default branch
            const todaysDate = new Date().toISOString().split('T')[0];

            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Fixed Style Changes ${todaysDate}`,
              head: headBranch,
              base: baseBranch,
              body: 'This PR fixes style changes',
            });
