name: Create Image on Dispatch

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Event Date (YYYY-MM-DD)'
        required: true
      image:
        description: 'Image Type (banner, meetup-image)'
        default: banner, meetup-image
        type: string

jobs:
  create-image-on-dispatch:
    uses: ./.github/workflows/create-image-shared.yml
    with:
      date: ${{ github.event.inputs.date }}
      image: ${{ github.event.inputs.image }}
