name: Style Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Set this to the node version you are using

      - name: Install dependencies
        run: npm install

      - name: Run style check
        run: npm run style

      - name: Run lintpkg
        run: npm run lintpkg

      - name: Run Build
        run: npm run build
